#!/usr/bin/env bash
#script that displays information about my subdomain
function subdomain() {
    #display information about a subdomain
    if [ -n "$1" ] && [ -n "$2" ]; then
        output=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:')
        read -r record subd destination <<< "$(awk 'NR==2 {print $4, $1, $5}' <<< "$output")"
        substr=${subd%%.*}
        echo "The subdomain $substr is a $record record and points to $destination"
    elif [ "$1" ]; then
        list=(www lb-01 web-01 web-02)
        for items in "${list[@]}"
        do
            output=$(dig "$items.$1" | grep -A1 'ANSWER SECTION:')
            read -r record subd destination <<< "$(awk 'NR==2 {print $4, $1, $5}' <<< "$output")"
            substr=${subd%%.*}
            echo "The subdomain $substr is a $record record and points to $destination"
        done
    fi
}

subdomain "$1" "$2"
