#!/usr/bin/env bash
#configures a server so that its http response contsins a header on web-01
HOSTNAME=$(hostname)
sudo sed -i "/http {/a \ \ \ \ \ \ \ \ add_header X-Served-By $HOSTNAME;\n" /etc/nginx/nginx.conf
sudo service nginx restart
