#!/usr/bin/bash
#install and configure HAproxy on my server
sudo apt-get update
sudo apt-get install haproxy -y

sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOF

frontend http-in
        bind *:80

backend mywebserver
        mode http
        balance roundrobin
        server 154541-web-01 54.237.35.136:80 check
        server 154541-web-02 18.209.224.238:80 check
EOF
sudo service haproxy restart

