#!/usr/bin/env bash
#generates a mysqldump and creates a compressed archive out of it
current_date=$(date +%d-%m-%Y)
sudo mysqldump -u root -p"$1" --all-databases > backup.sql
sudo tar -czf "$current_date".tar.gz backup.sql
