#!/usr/bin/env bash
# Displays "Best School" 10 times but best school and hi in the 9th iteration
i="0"
while [ $i -lt "10" ]; do
	if [ $i -eq "9" ]; then
		echo "Hi"
	fi
	echo "Best School"
	i=$((i+1))
done
