#!/usr/bin/env bash
# loops from 1 to 10 and displays something in the 4 and 8 iteration
export i="0"
for i in {0..9}; do
	if [ $i -eq "3" ]; then
		echo "bad luck"
	elif [ $i -eq "7" ]; then
		echo "good luck"
	else
		echo "Best School"
fi
done
