#!/usr/bin/env bash
# loops from 1 to 10 and displays something in the 4 and 8 iteration
i="0"
while [ $i -lt "9" ]; do
	if [ $i -eq "3" ]; then
		echo "bad luck"
		i=$((i+1))
	elif [ $i -eq "7" ]; then
		echo "good luck"
		i=$((i+1))
	else
		echo "Best School"
		i=$((i+1))
fi
done
