#!/usr/bin/env bash
# prints numbers from 1 to 20 and some string in a particular iteration
i="1"
while [ $i -lt 21 ]; do
	case $i  in
		"4")
			echo $i
			echo "bad luck from China"
			i=$((i+1));;
		"9")
			echo $i
			echo "bad luck from Japan"
			i=$((i+1));;
		"17")
			echo $i
			echo "bad luck from Italy"
			i=$((i+1));;
	esac
	echo $i
	i=$((i+1))
done
