#!/usr/bin/env bash
# prints numbers from 1 to 20 and some string in a particular iteration
for i in {1..20}; do
	if [ $i -eq "4" ]; then
		echo $i
		echo "bad luck from China"
		continue
	elif [ $i -eq "9" ]; then
		echo $i
		echo "bad luck from Japan"
		continue
	elif [ $i -eq "17" ]; then
		echo $i
		echo "bad luck from Italy"
		continue
	else
		echo $i
fi
done
