#!/usr/bin/env bash
#configures the container to run as nginx user litening on port 8080
sudo adduser --system --no-create-home --group nginx
sudo chown -R nginx:nginx /var/www
sudo service start nginx
listen 8080
